### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-angeles#2]
[Entrevista web 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-angeles/files/12541569/Entrevista.web.3.0.pdf)

**Comment by NoeliaGlez** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
